sudo: required
services:
  - docker
before_install:
  - docker build -t asb161/prod_docker_skeleton -f Dockerfile.dev .

script:
  - docker run asb161/prod_docker_skeleton npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "prod_docker_skeleton"
  env: "ProdDockerSkeleton-env"
  bucket_name: "elasticbeanstalk-us-east-2-823520053836"
  bucket_path: "prod_docker_skeleton"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
